USE customer_behavior;

-- customer_data == table  

SELECT * FROM customer_data;

# Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_data
GROUP BY gender;

# Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);

# Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) as 'Avg Product Rating'
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

# Q4. Compare the average purchase amount between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS  "average purchase amount"
FROM customer_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

# Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
SELECT subscription_status, COUNT(customer_id) AS 'total_customer', 
ROUND(AVG(purchase_amount), 2) AS 'Avg_purchase_amount',
ROUND(SUM(purchase_amount), 2) AS 'total_purchase_amount'
FROM customer_data
GROUP BY subscription_status
ORDER BY Avg_purchase_amount,total_purchase_amount DESC;

# Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100  AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC 
LIMIT 5;

# Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
	SELECT category, item_purchased,
    COUNT(customer_id) AS total_order,
    ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_order
FROM item_counts
WHERE item_rank <= 3;

# Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

# Q10. What is the revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;